# Generated by Django 4.1.1 on 2022-10-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_form_delete_material_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
    ]
