# Generated by Django 4.1.1 on 2022-10-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_material_user_delete_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
