# Generated by Django 4.1.1 on 2022-10-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0004_delete_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('M', 'Search with material'), ('SN', 'Search with serial number')], max_length=20)),
                ('serial_number', models.IntegerField()),
                ('item_number', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('commentary', models.TextField(max_length=300)),
            ],
        ),
    ]
